### ISSUE TITLE
About error and feature additions

### ISSUE THREAD

**Issue by cats-love** [jwdeveloper/JW_Piano#5]
![2022-07-29_00 21 40](https://user-images.githubusercontent.com/87476958/181595786-befe22b6-e896-451a-b787-a153c8d78ab7.png)
Hello, this is cats_love using the plugin on the Korean server. I wrote this to talk about some console errors and feature updates.

![image](https://user-images.githubusercontent.com/87476958/181595725-e4bf07a0-e05d-46a8-b200-5c9f727a0ac8.png)
First, clicking on the piano within the server causes the console log to go up badly. Is there any way to solve this problem?

Second, we ask if you plan to edit or add translations in the config, if you plan to add multiple piano colors, if you can use org.bukkit.inventory.ItemStack instead of a hoe to change item skins, and more!
Working with custommodeldata while making a wooden hoe available?

**Comment by cats-love** [comment]
![image](https://user-images.githubusercontent.com/87476958/181680341-b9a8651c-2bc2-4a02-b486-1aaff3f35419.png)
![image](https://user-images.githubusercontent.com/87476958/181680352-ac5976ee-7ea5-4393-a3f6-12701287a282.png)

There is one more problem, pressing the f key and releasing it will activate and deactivate the pedal. How do I stop interacting with the pedals?

**Comment by jwdeveloper** [comment]
Hi thank you for bugs report, 

<br />

> `First, clicking on the piano within the server causes the console log to go up badly. Is there any way to solve this problem?`

This issue is related to `multiverse` plugin and I'm currently working on fixing it :)
<br />

> `if you can use org.bukkit.inventory.ItemStack instead of a hoe to change item skins` 

 I don't really know if I understand this correctly but you do suggesting to make in `config` new section for custom skins?
 like? If so that's a great idea 👍 Unfrotunatelly I need to stick to one item type so propably I just change hoe to less used Item
```yaml 
  custom-skins:
    -new-skin:
      name: brand new piano
      modeldata: 2
```
<br />

> `edit or add translations`
I'm consider to include that but It will take so much time to implement so I don't think that will be possible for future updates

> `multiple piano colors`

 I feel custom skins section gives you opportunity to make the color as you want 
 <br />
`There is one more problem, pressing the f key and releasing it will activate and deactivate the pedal. How do I stop interacting with the pedals?` 
 
 Pressing pedal on `f` key is a feature, but I could make it optional 
<br />
Update ideas:

- [ ] Add sounds selection 'default(resource pack)/minecraft (vanilla minecraft sounds)` 
- [x] Add piano bench so player could sit down and play 
- [ ] More particle effects
- [x] New skins, `church organs`, `electric piano` 
- [ ] Sending MIDI file to server so there could be play in infninite loop 

If you would have more ideas let me know I would love to hear it!

**Comment by cats-love** [comment]
Also, the tp function is enabled even if there is no permission, so I would like to block it!

**Comment by cats-love** [comment]
![image](https://user-images.githubusercontent.com/87476958/181936211-8814bf13-934b-4004-a414-390d1281e265.png)
I want to use custommodeldata like this so that the piano and the wooden hoe do not overlap, but I don't know how..

**Comment by jwdeveloper** [comment]
hi, Custom skins are not yet implemented, but It will be soon possible

**Comment by jwdeveloper** [comment]
https://www.spigotmc.org/resources/piano.103490/
New update is avaliable

- Bugs you had resolved 
- Language support has been added 
- More permissions is added

!Custom skins are not ready yet!
